# Generated by Django 5.1.6 on 2025-03-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_brand_model_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
            preserve_default=False,
        ),
    ]
